### ISSUE TITLE
typeorm.d.ts file error

### ISSUE THREAD

**Issue by linkeyd** [forsigner/egg-typeorm#5]
>2 | import 'egg'
  3 | import { Repository, Connection } from 'typeorm'
 4 | import User from '../app\entity\user'
    |                                  ^
  5 | 
  6 | declare module 'egg' {
  7 |   interface Context {
    at e (D:\HomeDecoration\app_server\node_modules\prettier\parser-typescript.js:1:267)
    at Object.parse (D:\HomeDecoration\app_server\node_modules\prettier\parser-typescript.js:1:2261711)
    at Object.parse$2 [as parse] (D:\HomeDecoration\app_server\node_modules\prettier\index.js:10629:19)
    at coreFormat (D:\HomeDecoration\app_server\node_modules\prettier\index.js:13888:23)
    at format (D:\HomeDecoration\app_server\node_modules\prettier\index.js:14146:73)
    at formatWithCursor (D:\HomeDecoration\app_server\node_modules\prettier\index.js:14162:12)
    at D:\HomeDecoration\app_server\node_modules\prettier\index.js:42756:15
    at Object.format (D:\HomeDecoration\app_server\node_modules\prettier\index.js:42775:12)
    at formatCode (D:\HomeDecoration\app_server\node_modules\@forsigner\egg-typeorm\app.ts:10:19)
    at writeTyping (D:\HomeDecoration\app_server\node_modules\@forsigner\egg-typeorm\app.ts:36:26)

formatPaths  replace(reg, "\/");

>function formatPaths(files) {
    return files.map(file => {
        const name = getModelName(file);
        const reg = /\\/g;
        const importPath = `../${file}`.replace(/\.ts$|\.js$/g, '').replace(reg, "\/");
        return {
            name,
            importPath,
        };
    });
}

NODE.JS 8.11
Typescript 2.8+

**Comment by forsigner** [comment]
没考虑window，path.sep 的问题，明天更新一个版本

**Comment by forsigner** [comment]
@linkeyd fixed in v1.3.1

**Comment by linkeyd** [comment]
OK.
